create table
  public.Image (
    fid bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null default now(),
    url character varying null default 'NULL'::character varying,
    deleted boolean null default false,
    status public.status_enum null default 'Pending'::status_enum,
    likes array null,
    constraint Image_pkey primary key (fid)
  ) tablespace pg_default;