create table
  public.User (
    id bigint generated by default as identity not null,
    name character varying null,
    isAdmin boolean null,
    slug text not null,
    attendance jsonb not null,
    connection text null,
    language text null default 'en'::text,
    constraint User_pkey primary key (id),
    constraint User_slug_key unique (slug)
  ) tablespace pg_default;